# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_SPL_FIP_IO) += io_storage.o
obj-$(CONFIG_SPL_FIP_IO) += io_fip.o
obj-$(CONFIG_SPL_FIP_IO_DUMMY) += io_dummy.o
obj-$(CONFIG_SPL_FIP_IO_MEMORY) += io_memmap.o
obj-$(CONFIG_SPL_FIP_IO_BLOCK) += io_block.o
